global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
#### TODO
  - job_name: "pushgateway"
    static_configs:
    - targets: ["localhost:9091"]
